CREATE TABLE books (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '教材ID',
    title VARCHAR(100) NOT NULL COMMENT '教材名称',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
);

CREATE TABLE chapters (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '章节ID',
    book_id BIGINT NOT NULL COMMENT '所属教材ID',
    parent_id BIGINT DEFAULT NULL COMMENT '父章节ID',
    title VARCHAR(100) NOT NULL COMMENT '章节名称',
    level TINYINT NOT NULL COMMENT '章节层级: 1=章, 2=节',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE
);

CREATE TABLE files (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '文件ID',
    chapter_id BIGINT NOT NULL COMMENT '所属章节ID',
    file_name VARCHAR(200) NOT NULL COMMENT '文件名',
    minio_file_name VARCHAR(500) NOT NULL COMMENT 'minio文件名',
    bucket_name VARCHAR(100) NOT NULL COMMENT 'minio bucket名',
    type VARCHAR(50) NOT NULL COMMENT '文件类型（如PDF、PPT）',
    size BIGINT COMMENT '文件大小（字节）',
    path VARCHAR(500) NOT NULL COMMENT '文件存储路径',
    created_at datetime DEFAULT CURRENT_TIMESTAMP COMMENT '上传时间',
    FOREIGN KEY (chapter_id) REFERENCES chapters(id) ON DELETE CASCADE
);

CREATE TABLE users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '用户ID',
    username VARCHAR(50) NOT NULL UNIQUE COMMENT '用户名',
    password VARCHAR(255) NOT NULL COMMENT '加密密码',
    role ENUM('ADMIN', 'USER') NOT NULL COMMENT '用户角色',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
);

CREATE TABLE menus (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '菜单ID',
    `key` VARCHAR(50) NOT NULL UNIQUE COMMENT '菜单唯一标识',
    label VARCHAR(255) NOT NULL COMMENT '菜单名称',
    parent_id BIGINT DEFAULT NULL COMMENT '父菜单ID',
    icon VARCHAR(255) DEFAULT NULL COMMENT '菜单图标',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
);

CREATE TABLE role_menu (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    role ENUM('ADMIN', 'USER') NOT NULL COMMENT '角色',
    menu_id BIGINT NOT NULL COMMENT '菜单ID',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    FOREIGN KEY (menu_id) REFERENCES menus(id) ON DELETE CASCADE
);

CREATE TABLE note (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    title VARCHAR(255) NOT NULL COMMENT '笔记标题',
    content TEXT NOT NULL COMMENT '笔记内容',
		chapter_id BIGINT NOT NULL COMMENT '所属章节号',
    note_type ENUM('materials', 'exercises') NOT NULL COMMENT '笔记类型',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
);

CREATE TABLE daily_question (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '每日一题ID',
    file_id BIGINT NOT NULL COMMENT '题目文件ID，关联文件表',
    publish_date DATE NOT NULL UNIQUE COMMENT '发布日期，每天只允许一题',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    FOREIGN KEY (file_id) REFERENCES files(id) ON DELETE CASCADE
) COMMENT='每日一题表';